In [1]:
import numpy as np
import pandas as pd

In [5]:
xl = pd.ExcelFile('Table_1_03_A.xlsx')
xl.sheet_names

['Table_1_03_A']

In [6]:
df = xl.parse(xl.sheet_names[0])

In [7]:
df

,Table 1.3.A. Utility Scale Facility Net Generation,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,"by State, by Sector, January 2018 and 2017 (Th...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,All Sectors,NaN,NaN,Electric Power Sector,NaN,NaN,NaN,Commercial Sector,NaN,Industrial Sector,NaN
2,\n \n,\n \n,NaN,NaN,Electric Utilities,NaN,Independent\nPower Producers,NaN,NaN,NaN,NaN,NaN
3,\n \n \n,Generation at Utility Scale Facilities,NaN,NaN,Generation at Utility Scale Facilities,NaN,Generation at Utility Scale Facilities,NaN,Generation at Utility Scale Facilities,NaN,Generation at Utility Scale Facilities,NaN
4,Census Division\nand State,January 2018,January 2017,Percentage\nChange,January 2018,January 2017,January 2018,January 2017,January 2018,January 2017,January 2018,January 2017
5,New England,9590,8730,0.099,558,207,8673,8165,105,108,254,250
6,Connecticut,3406,3236,0.053,7,7,3331,3152,28,32,40,45
7,Maine,1102,921,0.197,0,0,898,726,17,16,188,179
8,Massachusetts,2713,2659,0.02,88,25,2553,2561,NM,49,24,23
9,New Hampshire,1729,1423,0.215,372,96,1347,1318,7,7,3,2
10,Rhode Island,450,318,0.414,0,1,445,313,5,4,0,0
11,Vermont,190,174,0.093,91,79,98,95,0.4,0.39,0,0
12,Middle Atlantic,37147,34018,0.092,3310,2789,33281,30666,187,175,369,387
13,New Jersey,5985,6133,-0.024,10,2,5855,6013,54,51,66,67
14,New York,12011,10399,0.155,3289,2780,8556,7449,92,97,75,73
15,Pennsylvania,19151,17486,0.095,10,7,18870,17204,42,28,228,247
16,East North Central,58072,51574,0.126,24881,21791,32072,28677,166,160,952,946
17,Illinois,17526,16523,0.061,481,424,16760,15808,40,32,245,260
18,Indiana,11193,9511,0.177,9521,8211,1284,920,22,21,367,359
19,Michigan,11057,9694,0.141,7768,7089,3086,2420,77,69,126,117
20,Ohio,12117,10124,0.197,2193,1555,9848,8484,18,25,58,60
21,Wisconsin,6180,5722,0.08,4919,4512,1095,1045,10,13,156,152
22,West North Central,33237,30885,0.076,26645,25915,6123,4540,59,55,410,375
23,Iowa,5828,5288,0.102,4317,4071,1314,1031,21,19,176,167
24,Kansas,4702,4453,0.056,3046,3092,1631,1356,NM,NM,24,NM
25,Minnesota,6068,5503,0.103,4695,4468,1203,863,20,19,150,153
26,Missouri,8057,7842,0.027,7634,7628,403,196,15,14,5,5
27,Nebraska,3399,3360,0.012,2747,2882,612,442,1,2,38,34
28,North Dakota,4108,3543,0.16,3378,3060,714,469,0.06,0,16,13
29,South Dakota,1075,897,0.199,828,713,247,184,NM,NM,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
38,Virginia,9323,8141,0.145,7625,6894,1457,1015,34,34,208,199
39,West Virginia,7145,7059,0.012,5490,5303,1574,1665,0,0,81,91
40,East South Central,35371,29290,0.208,30549,25804,4026,2710,19,18,777,758
41,Alabama,13217,10940,0.208,9717,8454,3126,2121,0,0,373,365
42,Kentucky,7595,6985,0.087,7425,6910,116,23,0,0,54,52
43,Mississippi,6157,4193,0.468,5221,3475,765,552,3,2,167,163
44,Tennessee,8402,7173,0.171,8185,6965,18,14,16,16,183,178
45,West South Central,61608,54797,0.124,19963,18170,35012,30009,66,71,6566,6546
46,Arkansas,6281,5413,0.16,4564,4679,1557,579,1,1,159,156
47,Louisiana,8610,8101,0.063,4907,4520,964,917,12,15,2726,2649
48,Oklahoma,7049,6282,0.122,3199,3467,3771,2739,0,0,79,76
49,Texas,39668,35000,0.133,7293,5505,28720,25775,54,55,3602,3665
50,Mountain,29672,31354,-0.054,22989,25403,6359,5642,46,43,279,266
51,Arizona,8192,7978,0.027,7501,7438,678,528,13,12,0,0
52,Colorado,4713,4967,-0.051,3555,3870,1151,1089,NM,NM,7,7
53,Idaho,1516,1395,0.087,958,947,498,391,5,5,55,53
54,Montana,2912,2740,0.063,1143,1070,1765,1667,0,0,3,4
55,Nevada,2810,3019,-0.069,1946,2241,833,752,9,8,23,18
56,New Mexico,2019,3140,-0.357,1143,2420,866,710,10,9,0,0.13
57,Utah,3136,3656,-0.142,2822,3338,253,258,8,7,54,53
58,Wyoming,4372,4458,-0.019,3922,4078,313,247,0,0,137,133
59,Pacific Contiguous,31871,34119,-0.066,20633,22605,9642,9950,248,257,1349,1308
60,California,14381,17445,-0.176,5976,8500,7015,7578,237,247,1152,1120
61,Oregon,5975,5927,0.008,4665,4581,1246,1285,7,7,57,54
62,Washington,11515,10747,0.071,9992,9523,1380,1087,4,3,139,133
63,Pacific Noncontiguous,1386,1372,0.01,965,978,323,293,69,65,29,36
64,Alaska,585,567,0.033,519,501,23,21,37,33,7,11
65,Hawaii,800,806,-0.006,446,477,301,272,32,32,22,25
66,U.S. Total,373213,341518,0.093,212947,198999,146536,128978,1078,1057,12652,12484
67,Displayed values of zero may represent small v...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# df1 = df
df1 = df.iloc[4:]

In [9]:
df1

,Table 1.3.A. Utility Scale Facility Net Generation,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
4,Census Division\nand State,January 2018,January 2017,Percentage\nChange,January 2018,January 2017,January 2018,January 2017,January 2018,January 2017,January 2018,January 2017
5,New England,9590,8730,0.099,558,207,8673,8165,105,108,254,250
6,Connecticut,3406,3236,0.053,7,7,3331,3152,28,32,40,45
7,Maine,1102,921,0.197,0,0,898,726,17,16,188,179
8,Massachusetts,2713,2659,0.02,88,25,2553,2561,NM,49,24,23
9,New Hampshire,1729,1423,0.215,372,96,1347,1318,7,7,3,2
10,Rhode Island,450,318,0.414,0,1,445,313,5,4,0,0
11,Vermont,190,174,0.093,91,79,98,95,0.4,0.39,0,0
12,Middle Atlantic,37147,34018,0.092,3310,2789,33281,30666,187,175,369,387
13,New Jersey,5985,6133,-0.024,10,2,5855,6013,54,51,66,67
14,New York,12011,10399,0.155,3289,2780,8556,7449,92,97,75,73
15,Pennsylvania,19151,17486,0.095,10,7,18870,17204,42,28,228,247
16,East North Central,58072,51574,0.126,24881,21791,32072,28677,166,160,952,946
17,Illinois,17526,16523,0.061,481,424,16760,15808,40,32,245,260
18,Indiana,11193,9511,0.177,9521,8211,1284,920,22,21,367,359
19,Michigan,11057,9694,0.141,7768,7089,3086,2420,77,69,126,117
20,Ohio,12117,10124,0.197,2193,1555,9848,8484,18,25,58,60
21,Wisconsin,6180,5722,0.08,4919,4512,1095,1045,10,13,156,152
22,West North Central,33237,30885,0.076,26645,25915,6123,4540,59,55,410,375
23,Iowa,5828,5288,0.102,4317,4071,1314,1031,21,19,176,167
24,Kansas,4702,4453,0.056,3046,3092,1631,1356,NM,NM,24,NM
25,Minnesota,6068,5503,0.103,4695,4468,1203,863,20,19,150,153
26,Missouri,8057,7842,0.027,7634,7628,403,196,15,14,5,5
27,Nebraska,3399,3360,0.012,2747,2882,612,442,1,2,38,34
28,North Dakota,4108,3543,0.16,3378,3060,714,469,0.06,0,16,13
29,South Dakota,1075,897,0.199,828,713,247,184,NM,NM,0,0
30,South Atlantic,75260,65379,0.151,62455,55337,11026,8325,112,104,1667,1613
31,Delaware,580,476,0.218,6,NM,503,364,NM,NM,70,111
32,District of Columbia,7,10,-0.286,0,0,4,5,3,4,0,0
33,Florida,19606,17547,0.117,18018,16245,1125,862,7,7,456,433
...,...,...,...,...,...,...,...,...,...,...,...,...
38,Virginia,9323,8141,0.145,7625,6894,1457,1015,34,34,208,199
39,West Virginia,7145,7059,0.012,5490,5303,1574,1665,0,0,81,91
40,East South Central,35371,29290,0.208,30549,25804,4026,2710,19,18,777,758
41,Alabama,13217,10940,0.208,9717,8454,3126,2121,0,0,373,365
42,Kentucky,7595,6985,0.087,7425,6910,116,23,0,0,54,52
43,Mississippi,6157,4193,0.468,5221,3475,765,552,3,2,167,163
44,Tennessee,8402,7173,0.171,8185,6965,18,14,16,16,183,178
45,West South Central,61608,54797,0.124,19963,18170,35012,30009,66,71,6566,6546
46,Arkansas,6281,5413,0.16,4564,4679,1557,579,1,1,159,156
47,Louisiana,8610,8101,0.063,4907,4520,964,917,12,15,2726,2649
48,Oklahoma,7049,6282,0.122,3199,3467,3771,2739,0,0,79,76
49,Texas,39668,35000,0.133,7293,5505,28720,25775,54,55,3602,3665
50,Mountain,29672,31354,-0.054,22989,25403,6359,5642,46,43,279,266
51,Arizona,8192,7978,0.027,7501,7438,678,528,13,12,0,0
52,Colorado,4713,4967,-0.051,3555,3870,1151,1089,NM,NM,7,7
53,Idaho,1516,1395,0.087,958,947,498,391,5,5,55,53
54,Montana,2912,2740,0.063,1143,1070,1765,1667,0,0,3,4
55,Nevada,2810,3019,-0.069,1946,2241,833,752,9,8,23,18
56,New Mexico,2019,3140,-0.357,1143,2420,866,710,10,9,0,0.13
57,Utah,3136,3656,-0.142,2822,3338,253,258,8,7,54,53
58,Wyoming,4372,4458,-0.019,3922,4078,313,247,0,0,137,133
59,Pacific Contiguous,31871,34119,-0.066,20633,22605,9642,9950,248,257,1349,1308
60,California,14381,17445,-0.176,5976,8500,7015,7578,237,247,1152,1120
61,Oregon,5975,5927,0.008,4665,4581,1246,1285,7,7,57,54
62,Washington,11515,10747,0.071,9992,9523,1380,1087,4,3,139,133
63,Pacific Noncontiguous,1386,1372,0.01,965,978,323,293,69,65,29,36
64,Alaska,585,567,0.033,519,501,23,21,37,33,7,11
65,Hawaii,800,806,-0.006,446,477,301,272,32,32,22,25
66,U.S. Total,373213,341518,0.093,212947,198999,146536,128978,1078,1057,12652,12484
67,Displayed values of zero may represent small v...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
new_header = df1.iloc[0]
new_header

Table 1.3.A. Utility Scale Facility Net Generation    Census Division\nand State
Unnamed: 1                                                          January 2018
Unnamed: 2                                                          January 2017
Unnamed: 3                                                    Percentage\nChange
Unnamed: 4                                                          January 2018
Unnamed: 5                                                          January 2017
Unnamed: 6                                                          January 2018
Unnamed: 7                                                          January 2017
Unnamed: 8                                                          January 2018
Unnamed: 9                                                          January 2017
Unnamed: 10                                                         January 2018
Unnamed: 11                                                         January 2017
Name: 4, dtype: object

In [11]:
df2 = df1[1:]

In [12]:
df2

,Table 1.3.A. Utility Scale Facility Net Generation,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
5,New England,9590,8730,0.099,558,207,8673,8165,105,108,254,250
6,Connecticut,3406,3236,0.053,7,7,3331,3152,28,32,40,45
7,Maine,1102,921,0.197,0,0,898,726,17,16,188,179
8,Massachusetts,2713,2659,0.02,88,25,2553,2561,NM,49,24,23
9,New Hampshire,1729,1423,0.215,372,96,1347,1318,7,7,3,2
10,Rhode Island,450,318,0.414,0,1,445,313,5,4,0,0
11,Vermont,190,174,0.093,91,79,98,95,0.4,0.39,0,0
12,Middle Atlantic,37147,34018,0.092,3310,2789,33281,30666,187,175,369,387
13,New Jersey,5985,6133,-0.024,10,2,5855,6013,54,51,66,67
14,New York,12011,10399,0.155,3289,2780,8556,7449,92,97,75,73
15,Pennsylvania,19151,17486,0.095,10,7,18870,17204,42,28,228,247
16,East North Central,58072,51574,0.126,24881,21791,32072,28677,166,160,952,946
17,Illinois,17526,16523,0.061,481,424,16760,15808,40,32,245,260
18,Indiana,11193,9511,0.177,9521,8211,1284,920,22,21,367,359
19,Michigan,11057,9694,0.141,7768,7089,3086,2420,77,69,126,117
20,Ohio,12117,10124,0.197,2193,1555,9848,8484,18,25,58,60
21,Wisconsin,6180,5722,0.08,4919,4512,1095,1045,10,13,156,152
22,West North Central,33237,30885,0.076,26645,25915,6123,4540,59,55,410,375
23,Iowa,5828,5288,0.102,4317,4071,1314,1031,21,19,176,167
24,Kansas,4702,4453,0.056,3046,3092,1631,1356,NM,NM,24,NM
25,Minnesota,6068,5503,0.103,4695,4468,1203,863,20,19,150,153
26,Missouri,8057,7842,0.027,7634,7628,403,196,15,14,5,5
27,Nebraska,3399,3360,0.012,2747,2882,612,442,1,2,38,34
28,North Dakota,4108,3543,0.16,3378,3060,714,469,0.06,0,16,13
29,South Dakota,1075,897,0.199,828,713,247,184,NM,NM,0,0
30,South Atlantic,75260,65379,0.151,62455,55337,11026,8325,112,104,1667,1613
31,Delaware,580,476,0.218,6,NM,503,364,NM,NM,70,111
32,District of Columbia,7,10,-0.286,0,0,4,5,3,4,0,0
33,Florida,19606,17547,0.117,18018,16245,1125,862,7,7,456,433
34,Georgia,12180,10303,0.182,10510,8965,1199,916,3,NM,468,421
...,...,...,...,...,...,...,...,...,...,...,...,...
38,Virginia,9323,8141,0.145,7625,6894,1457,1015,34,34,208,199
39,West Virginia,7145,7059,0.012,5490,5303,1574,1665,0,0,81,91
40,East South Central,35371,29290,0.208,30549,25804,4026,2710,19,18,777,758
41,Alabama,13217,10940,0.208,9717,8454,3126,2121,0,0,373,365
42,Kentucky,7595,6985,0.087,7425,6910,116,23,0,0,54,52
43,Mississippi,6157,4193,0.468,5221,3475,765,552,3,2,167,163
44,Tennessee,8402,7173,0.171,8185,6965,18,14,16,16,183,178
45,West South Central,61608,54797,0.124,19963,18170,35012,30009,66,71,6566,6546
46,Arkansas,6281,5413,0.16,4564,4679,1557,579,1,1,159,156
47,Louisiana,8610,8101,0.063,4907,4520,964,917,12,15,2726,2649
48,Oklahoma,7049,6282,0.122,3199,3467,3771,2739,0,0,79,76
49,Texas,39668,35000,0.133,7293,5505,28720,25775,54,55,3602,3665
50,Mountain,29672,31354,-0.054,22989,25403,6359,5642,46,43,279,266
51,Arizona,8192,7978,0.027,7501,7438,678,528,13,12,0,0
52,Colorado,4713,4967,-0.051,3555,3870,1151,1089,NM,NM,7,7
53,Idaho,1516,1395,0.087,958,947,498,391,5,5,55,53
54,Montana,2912,2740,0.063,1143,1070,1765,1667,0,0,3,4
55,Nevada,2810,3019,-0.069,1946,2241,833,752,9,8,23,18
56,New Mexico,2019,3140,-0.357,1143,2420,866,710,10,9,0,0.13
57,Utah,3136,3656,-0.142,2822,3338,253,258,8,7,54,53
58,Wyoming,4372,4458,-0.019,3922,4078,313,247,0,0,137,133
59,Pacific Contiguous,31871,34119,-0.066,20633,22605,9642,9950,248,257,1349,1308
60,California,14381,17445,-0.176,5976,8500,7015,7578,237,247,1152,1120
61,Oregon,5975,5927,0.008,4665,4581,1246,1285,7,7,57,54
62,Washington,11515,10747,0.071,9992,9523,1380,1087,4,3,139,133
63,Pacific Noncontiguous,1386,1372,0.01,965,978,323,293,69,65,29,36
64,Alaska,585,567,0.033,519,501,23,21,37,33,7,11
65,Hawaii,800,806,-0.006,446,477,301,272,32,32,22,25
66,U.S. Total,373213,341518,0.093,212947,198999,146536,128978,1078,1057,12652,12484
67,Displayed values of zero may represent small v...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df2.columns = new_header 
df2

4,Census Division and State,January 2018,January 2017,Percentage Change,January 2018,January 2017,January 2018,January 2017,January 2018,January 2017,January 2018,January 2017
5,New England,9590,8730,0.099,558,207,8673,8165,105,108,254,250
6,Connecticut,3406,3236,0.053,7,7,3331,3152,28,32,40,45
7,Maine,1102,921,0.197,0,0,898,726,17,16,188,179
8,Massachusetts,2713,2659,0.02,88,25,2553,2561,NM,49,24,23
9,New Hampshire,1729,1423,0.215,372,96,1347,1318,7,7,3,2
10,Rhode Island,450,318,0.414,0,1,445,313,5,4,0,0
11,Vermont,190,174,0.093,91,79,98,95,0.4,0.39,0,0
12,Middle Atlantic,37147,34018,0.092,3310,2789,33281,30666,187,175,369,387
13,New Jersey,5985,6133,-0.024,10,2,5855,6013,54,51,66,67
14,New York,12011,10399,0.155,3289,2780,8556,7449,92,97,75,73
15,Pennsylvania,19151,17486,0.095,10,7,18870,17204,42,28,228,247
16,East North Central,58072,51574,0.126,24881,21791,32072,28677,166,160,952,946
17,Illinois,17526,16523,0.061,481,424,16760,15808,40,32,245,260
18,Indiana,11193,9511,0.177,9521,8211,1284,920,22,21,367,359
19,Michigan,11057,9694,0.141,7768,7089,3086,2420,77,69,126,117
20,Ohio,12117,10124,0.197,2193,1555,9848,8484,18,25,58,60
21,Wisconsin,6180,5722,0.08,4919,4512,1095,1045,10,13,156,152
22,West North Central,33237,30885,0.076,26645,25915,6123,4540,59,55,410,375
23,Iowa,5828,5288,0.102,4317,4071,1314,1031,21,19,176,167
24,Kansas,4702,4453,0.056,3046,3092,1631,1356,NM,NM,24,NM
25,Minnesota,6068,5503,0.103,4695,4468,1203,863,20,19,150,153
26,Missouri,8057,7842,0.027,7634,7628,403,196,15,14,5,5
27,Nebraska,3399,3360,0.012,2747,2882,612,442,1,2,38,34
28,North Dakota,4108,3543,0.16,3378,3060,714,469,0.06,0,16,13
29,South Dakota,1075,897,0.199,828,713,247,184,NM,NM,0,0
30,South Atlantic,75260,65379,0.151,62455,55337,11026,8325,112,104,1667,1613
31,Delaware,580,476,0.218,6,NM,503,364,NM,NM,70,111
32,District of Columbia,7,10,-0.286,0,0,4,5,3,4,0,0
33,Florida,19606,17547,0.117,18018,16245,1125,862,7,7,456,433
34,Georgia,12180,10303,0.182,10510,8965,1199,916,3,NM,468,421
...,...,...,...,...,...,...,...,...,...,...,...,...
38,Virginia,9323,8141,0.145,7625,6894,1457,1015,34,34,208,199
39,West Virginia,7145,7059,0.012,5490,5303,1574,1665,0,0,81,91
40,East South Central,35371,29290,0.208,30549,25804,4026,2710,19,18,777,758
41,Alabama,13217,10940,0.208,9717,8454,3126,2121,0,0,373,365
42,Kentucky,7595,6985,0.087,7425,6910,116,23,0,0,54,52
43,Mississippi,6157,4193,0.468,5221,3475,765,552,3,2,167,163
44,Tennessee,8402,7173,0.171,8185,6965,18,14,16,16,183,178
45,West South Central,61608,54797,0.124,19963,18170,35012,30009,66,71,6566,6546
46,Arkansas,6281,5413,0.16,4564,4679,1557,579,1,1,159,156
47,Louisiana,8610,8101,0.063,4907,4520,964,917,12,15,2726,2649
48,Oklahoma,7049,6282,0.122,3199,3467,3771,2739,0,0,79,76
49,Texas,39668,35000,0.133,7293,5505,28720,25775,54,55,3602,3665
50,Mountain,29672,31354,-0.054,22989,25403,6359,5642,46,43,279,266
51,Arizona,8192,7978,0.027,7501,7438,678,528,13,12,0,0
52,Colorado,4713,4967,-0.051,3555,3870,1151,1089,NM,NM,7,7
53,Idaho,1516,1395,0.087,958,947,498,391,5,5,55,53
54,Montana,2912,2740,0.063,1143,1070,1765,1667,0,0,3,4
55,Nevada,2810,3019,-0.069,1946,2241,833,752,9,8,23,18
56,New Mexico,2019,3140,-0.357,1143,2420,866,710,10,9,0,0.13
57,Utah,3136,3656,-0.142,2822,3338,253,258,8,7,54,53
58,Wyoming,4372,4458,-0.019,3922,4078,313,247,0,0,137,133
59,Pacific Contiguous,31871,34119,-0.066,20633,22605,9642,9950,248,257,1349,1308
60,California,14381,17445,-0.176,5976,8500,7015,7578,237,247,1152,1120
61,Oregon,5975,5927,0.008,4665,4581,1246,1285,7,7,57,54
62,Washington,11515,10747,0.071,9992,9523,1380,1087,4,3,139,133
63,Pacific Noncontiguous,1386,1372,0.01,965,978,323,293,69,65,29,36
64,Alaska,585,567,0.033,519,501,23,21,37,33,7,11
65,Hawaii,800,806,-0.006,446,477,301,272,32,32,22,25
66,U.S. Total,373213,341518,0.093,212947,198999,146536,128978,1078,1057,12652,12484
67,Displayed values of zero may represent small v...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df3 = df2.iloc[:, range(4)]

In [32]:
df3

4,Census Division and State,January 2018,January 2017,Percentage Change
5,New England,9590,8730,0.099
6,Connecticut,3406,3236,0.053
7,Maine,1102,921,0.197
8,Massachusetts,2713,2659,0.02
9,New Hampshire,1729,1423,0.215
10,Rhode Island,450,318,0.414
11,Vermont,190,174,0.093
12,Middle Atlantic,37147,34018,0.092
13,New Jersey,5985,6133,-0.024
14,New York,12011,10399,0.155
15,Pennsylvania,19151,17486,0.095
16,East North Central,58072,51574,0.126
17,Illinois,17526,16523,0.061
18,Indiana,11193,9511,0.177
19,Michigan,11057,9694,0.141
20,Ohio,12117,10124,0.197
21,Wisconsin,6180,5722,0.08
22,West North Central,33237,30885,0.076
23,Iowa,5828,5288,0.102
24,Kansas,4702,4453,0.056
25,Minnesota,6068,5503,0.103
26,Missouri,8057,7842,0.027
27,Nebraska,3399,3360,0.012
28,North Dakota,4108,3543,0.16
29,South Dakota,1075,897,0.199
30,South Atlantic,75260,65379,0.151
31,Delaware,580,476,0.218
32,District of Columbia,7,10,-0.286
33,Florida,19606,17547,0.117
34,Georgia,12180,10303,0.182
...,...,...,...,...
38,Virginia,9323,8141,0.145
39,West Virginia,7145,7059,0.012
40,East South Central,35371,29290,0.208
41,Alabama,13217,10940,0.208
42,Kentucky,7595,6985,0.087
43,Mississippi,6157,4193,0.468
44,Tennessee,8402,7173,0.171
45,West South Central,61608,54797,0.124
46,Arkansas,6281,5413,0.16
47,Louisiana,8610,8101,0.063
48,Oklahoma,7049,6282,0.122
49,Texas,39668,35000,0.133
50,Mountain,29672,31354,-0.054
51,Arizona,8192,7978,0.027
52,Colorado,4713,4967,-0.051
53,Idaho,1516,1395,0.087
54,Montana,2912,2740,0.063
55,Nevada,2810,3019,-0.069
56,New Mexico,2019,3140,-0.357
57,Utah,3136,3656,-0.142
58,Wyoming,4372,4458,-0.019
59,Pacific Contiguous,31871,34119,-0.066
60,California,14381,17445,-0.176
61,Oregon,5975,5927,0.008
62,Washington,11515,10747,0.071
63,Pacific Noncontiguous,1386,1372,0.01
64,Alaska,585,567,0.033
65,Hawaii,800,806,-0.006
66,U.S. Total,373213,341518,0.093
67,Displayed values of zero may represent small v...,NaN,NaN,NaN

In [33]:
df3.columns

Index(['Census Division\nand State', 'January 2018', 'January 2017',
       'Percentage\nChange'],
      dtype='object', name=4)

In [34]:
mask = (df3['Census Division\nand State'] != 'Middle Atlantic') &\
(df3['Census Division\nand State'] !='East North Central') &\
(df3['Census Division\nand State'] !='West North Central') &\
(df3['Census Division\nand State'] !='South Atlantic') &\
(df3['Census Division\nand State'] !='East South Central') &\
(df3['Census Division\nand State'] !='West South Central') &\
(df3['Census Division\nand State'] !='Mountain') &\
(df3['Census Division\nand State'] !='Pacific Contiguous') &\
(df3['Census Division\nand State'] !='Pacific Noncontiguous') &\
(df3['Census Division\nand State'] !='U.S. Total')

In [39]:
df4=df3[mask].dropna(how='any')

In [40]:
df4

4  Census Division\nand State January 2018 January 2017 Percentage\nChange
5                 New England         9590         8730              0.099
6                 Connecticut         3406         3236              0.053
7                       Maine         1102          921              0.197
8               Massachusetts         2713         2659               0.02
9               New Hampshire         1729         1423              0.215
10               Rhode Island          450          318              0.414
11                    Vermont          190          174              0.093
13                 New Jersey         5985         6133             -0.024
14                   New York        12011        10399              0.155
15               Pennsylvania        19151        17486              0.095
17                   Illinois        17526        16523              0.061
18                    Indiana        11193         9511              0.177
19                   Michigan        11057         9694              0.141
20                       Ohio        12117        10124              0.197
21                  Wisconsin         6180         5722               0.08
23                       Iowa         5828         5288              0.102
24                     Kansas         4702         4453              0.056
25                  Minnesota         6068         5503              0.103
26                   Missouri         8057         7842              0.027
27                   Nebraska         3399         3360              0.012
28               North Dakota         4108         3543               0.16
29               South Dakota         1075          897              0.199
31                   Delaware          580          476              0.218
32       District of Columbia            7           10             -0.286
33                    Florida        19606        17547              0.117
34                    Georgia        12180        10303              0.182
35                   Maryland         4049         2692              0.504
36             North Carolina        13316        10912               0.22
37             South Carolina         9055         8240              0.099
38                   Virginia         9323         8141              0.145
39              West Virginia         7145         7059              0.012
41                    Alabama        13217        10940              0.208
42                   Kentucky         7595         6985              0.087
43                Mississippi         6157         4193              0.468
44                  Tennessee         8402         7173              0.171
46                   Arkansas         6281         5413               0.16
47                  Louisiana         8610         8101              0.063
48                   Oklahoma         7049         6282              0.122
49                      Texas        39668        35000              0.133
51                    Arizona         8192         7978              0.027
52                   Colorado         4713         4967             -0.051
53                      Idaho         1516         1395              0.087
54                    Montana         2912         2740              0.063
55                     Nevada         2810         3019             -0.069
56                 New Mexico         2019         3140             -0.357
57                       Utah         3136         3656             -0.142
58                    Wyoming         4372         4458             -0.019
60                 California        14381        17445             -0.176
61                     Oregon         5975         5927              0.008
62                 Washington        11515        10747              0.071
64                     Alaska          585          567              0.033
65                     Hawaii          800          806             -0.006

In [41]:
df4.rename(columns={'Census Division\nand State': 'state'}, inplace=True)
# df4.rename(index=str, columns={"": "state"})
df4

4                  state January 2018 January 2017 Percentage\nChange
5            New England         9590         8730              0.099
6            Connecticut         3406         3236              0.053
7                  Maine         1102          921              0.197
8          Massachusetts         2713         2659               0.02
9          New Hampshire         1729         1423              0.215
10          Rhode Island          450          318              0.414
11               Vermont          190          174              0.093
13            New Jersey         5985         6133             -0.024
14              New York        12011        10399              0.155
15          Pennsylvania        19151        17486              0.095
17              Illinois        17526        16523              0.061
18               Indiana        11193         9511              0.177
19              Michigan        11057         9694              0.141
20                  Ohio        12117        10124              0.197
21             Wisconsin         6180         5722               0.08
23                  Iowa         5828         5288              0.102
24                Kansas         4702         4453              0.056
25             Minnesota         6068         5503              0.103
26              Missouri         8057         7842              0.027
27              Nebraska         3399         3360              0.012
28          North Dakota         4108         3543               0.16
29          South Dakota         1075          897              0.199
31              Delaware          580          476              0.218
32  District of Columbia            7           10             -0.286
33               Florida        19606        17547              0.117
34               Georgia        12180        10303              0.182
35              Maryland         4049         2692              0.504
36        North Carolina        13316        10912               0.22
37        South Carolina         9055         8240              0.099
38              Virginia         9323         8141              0.145
39         West Virginia         7145         7059              0.012
41               Alabama        13217        10940              0.208
42              Kentucky         7595         6985              0.087
43           Mississippi         6157         4193              0.468
44             Tennessee         8402         7173              0.171
46              Arkansas         6281         5413               0.16
47             Louisiana         8610         8101              0.063
48              Oklahoma         7049         6282              0.122
49                 Texas        39668        35000              0.133
51               Arizona         8192         7978              0.027
52              Colorado         4713         4967             -0.051
53                 Idaho         1516         1395              0.087
54               Montana         2912         2740              0.063
55                Nevada         2810         3019             -0.069
56            New Mexico         2019         3140             -0.357
57                  Utah         3136         3656             -0.142
58               Wyoming         4372         4458             -0.019
60            California        14381        17445             -0.176
61                Oregon         5975         5927              0.008
62            Washington        11515        10747              0.071
64                Alaska          585          567              0.033
65                Hawaii          800          806             -0.006

In [42]:
df5 = df4[['state', 'January 2018']]
df5

4                  state January 2018
5            New England         9590
6            Connecticut         3406
7                  Maine         1102
8          Massachusetts         2713
9          New Hampshire         1729
10          Rhode Island          450
11               Vermont          190
13            New Jersey         5985
14              New York        12011
15          Pennsylvania        19151
17              Illinois        17526
18               Indiana        11193
19              Michigan        11057
20                  Ohio        12117
21             Wisconsin         6180
23                  Iowa         5828
24                Kansas         4702
25             Minnesota         6068
26              Missouri         8057
27              Nebraska         3399
28          North Dakota         4108
29          South Dakota         1075
31              Delaware          580
32  District of Columbia            7
33               Florida        19606
34               Georgia        12180
35              Maryland         4049
36        North Carolina        13316
37        South Carolina         9055
38              Virginia         9323
39         West Virginia         7145
41               Alabama        13217
42              Kentucky         7595
43           Mississippi         6157
44             Tennessee         8402
46              Arkansas         6281
47             Louisiana         8610
48              Oklahoma         7049
49                 Texas        39668
51               Arizona         8192
52              Colorado         4713
53                 Idaho         1516
54               Montana         2912
55                Nevada         2810
56            New Mexico         2019
57                  Utah         3136
58               Wyoming         4372
60            California        14381
61                Oregon         5975
62            Washington        11515
64                Alaska          585
65                Hawaii          800

In [44]:
states_hash ={
    'Alabama': 'AL',
    'Alaska': 'AK',
    'American Samoa': 'AS',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District Of Columbia': 'DC',
    'Federated States Of Micronesia': 'FM',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Guam': 'GU',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Marshall Islands': 'MH',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands': 'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Palau': 'PW',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
  }

In [47]:
df5['state'].map(states_hash)

5     NaN
6      CT
7      ME
8      MA
9      NH
10     RI
11     VT
13     NJ
14     NY
15     PA
17     IL
18     IN
19     MI
20     OH
21     WI
23     IA
24     KS
25     MN
26     MO
27     NE
28     ND
29     SD
31     DE
32    NaN
33     FL
34     GA
35     MD
36     NC
37     SC
38     VA
39     WV
41     AL
42     KY
43     MS
44     TN
46     AR
47     LA
48     OK
49     TX
51     AZ
52     CO
53     ID
54     MT
55     NV
56     NM
57     UT
58     WY
60     CA
61     OR
62     WA
64     AK
65     HI
Name: state, dtype: object

In [48]:
df5

4                  state January 2018
5            New England         9590
6            Connecticut         3406
7                  Maine         1102
8          Massachusetts         2713
9          New Hampshire         1729
10          Rhode Island          450
11               Vermont          190
13            New Jersey         5985
14              New York        12011
15          Pennsylvania        19151
17              Illinois        17526
18               Indiana        11193
19              Michigan        11057
20                  Ohio        12117
21             Wisconsin         6180
23                  Iowa         5828
24                Kansas         4702
25             Minnesota         6068
26              Missouri         8057
27              Nebraska         3399
28          North Dakota         4108
29          South Dakota         1075
31              Delaware          580
32  District of Columbia            7
33               Florida        19606
34               Georgia        12180
35              Maryland         4049
36        North Carolina        13316
37        South Carolina         9055
38              Virginia         9323
39         West Virginia         7145
41               Alabama        13217
42              Kentucky         7595
43           Mississippi         6157
44             Tennessee         8402
46              Arkansas         6281
47             Louisiana         8610
48              Oklahoma         7049
49                 Texas        39668
51               Arizona         8192
52              Colorado         4713
53                 Idaho         1516
54               Montana         2912
55                Nevada         2810
56            New Mexico         2019
57                  Utah         3136
58               Wyoming         4372
60            California        14381
61                Oregon         5975
62            Washington        11515
64                Alaska          585
65                Hawaii          800

In [28]:
df4

Census Division and State,Census Division and State,January 2018,January 2017,Percentage Change
5,New England,9590,8730,0.099
6,Connecticut,3406,3236,0.053
7,Maine,1102,921,0.197
8,Massachusetts,2713,2659,0.02
9,New Hampshire,1729,1423,0.215
10,Rhode Island,450,318,0.414
11,Vermont,190,174,0.093
13,New Jersey,5985,6133,-0.024
14,New York,12011,10399,0.155
15,Pennsylvania,19151,17486,0.095
17,Illinois,17526,16523,0.061
18,Indiana,11193,9511,0.177
19,Michigan,11057,9694,0.141
20,Ohio,12117,10124,0.197
21,Wisconsin,6180,5722,0.08
23,Iowa,5828,5288,0.102
24,Kansas,4702,4453,0.056
25,Minnesota,6068,5503,0.103
26,Missouri,8057,7842,0.027
27,Nebraska,3399,3360,0.012
28,North Dakota,4108,3543,0.16
29,South Dakota,1075,897,0.199
31,Delaware,580,476,0.218
32,District of Columbia,7,10,-0.286
33,Florida,19606,17547,0.117
34,Georgia,12180,10303,0.182
35,Maryland,4049,2692,0.504
36,North Carolina,13316,10912,0.22
37,South Carolina,9055,8240,0.099
38,Virginia,9323,8141,0.145
39,West Virginia,7145,7059,0.012
41,Alabama,13217,10940,0.208
42,Kentucky,7595,6985,0.087
43,Mississippi,6157,4193,0.468
44,Tennessee,8402,7173,0.171
46,Arkansas,6281,5413,0.16
47,Louisiana,8610,8101,0.063
48,Oklahoma,7049,6282,0.122
49,Texas,39668,35000,0.133
51,Arizona,8192,7978,0.027
52,Colorado,4713,4967,-0.051
53,Idaho,1516,1395,0.087
54,Montana,2912,2740,0.063
55,Nevada,2810,3019,-0.069
56,New Mexico,2019,3140,-0.357
57,Utah,3136,3656,-0.142
58,Wyoming,4372,4458,-0.019
60,California,14381,17445,-0.176
61,Oregon,5975,5927,0.008
62,Washington,11515,10747,0.071
64,Alaska,585,567,0.033
65,Hawaii,800,806,-0.006

In [21]:
df4.columns.rename('Census Division\nand State', 'state')

In [22]:
df4

Census Division and State,Census Division and State,January 2018,January 2017,Percentage Change
5,New England,9590,8730,0.099
6,Connecticut,3406,3236,0.053
7,Maine,1102,921,0.197
8,Massachusetts,2713,2659,0.02
9,New Hampshire,1729,1423,0.215
10,Rhode Island,450,318,0.414
11,Vermont,190,174,0.093
13,New Jersey,5985,6133,-0.024
14,New York,12011,10399,0.155
15,Pennsylvania,19151,17486,0.095
17,Illinois,17526,16523,0.061
18,Indiana,11193,9511,0.177
19,Michigan,11057,9694,0.141
20,Ohio,12117,10124,0.197
21,Wisconsin,6180,5722,0.08
23,Iowa,5828,5288,0.102
24,Kansas,4702,4453,0.056
25,Minnesota,6068,5503,0.103
26,Missouri,8057,7842,0.027
27,Nebraska,3399,3360,0.012
28,North Dakota,4108,3543,0.16
29,South Dakota,1075,897,0.199
31,Delaware,580,476,0.218
32,District of Columbia,7,10,-0.286
33,Florida,19606,17547,0.117
34,Georgia,12180,10303,0.182
35,Maryland,4049,2692,0.504
36,North Carolina,13316,10912,0.22
37,South Carolina,9055,8240,0.099
38,Virginia,9323,8141,0.145
39,West Virginia,7145,7059,0.012
41,Alabama,13217,10940,0.208
42,Kentucky,7595,6985,0.087
43,Mississippi,6157,4193,0.468
44,Tennessee,8402,7173,0.171
46,Arkansas,6281,5413,0.16
47,Louisiana,8610,8101,0.063
48,Oklahoma,7049,6282,0.122
49,Texas,39668,35000,0.133
51,Arizona,8192,7978,0.027
52,Colorado,4713,4967,-0.051
53,Idaho,1516,1395,0.087
54,Montana,2912,2740,0.063
55,Nevada,2810,3019,-0.069
56,New Mexico,2019,3140,-0.357
57,Utah,3136,3656,-0.142
58,Wyoming,4372,4458,-0.019
60,California,14381,17445,-0.176
61,Oregon,5975,5927,0.008
62,Washington,11515,10747,0.071
64,Alaska,585,567,0.033
65,Hawaii,800,806,-0.006